export enum MAITENANCE_TYPE {
  CORRECTIVO = 'CORRECTIVO',
  PREVENTIVO = 'PREVENTIVO',
}

export enum STATUS_MANTENANCE {
  EN_OPERACION = 'EN_OPERACION',
  EN_ALMACEN = 'EN_ALMACEN',
  DISPONIBLE = 'DISPONIBLE',
}
export enum ADD_REMOVE {
  ALTA = 'ALTA',
  BAJA = 'BAJA',
}

export enum STATUS_RESOURCE {
  TRAYECTO = 'TRAYECTO',
  ALMACEN = 'ALMACEN',
  DISPONIBLE = 'DISPONIBLE',
}