export enum STATUS_ADMISSION {
  ADMISSION = 'ADMISSION',
  DISCHARGE = 'DISCHARGE',
  REMOVE = 'REMOVE',
  ADD = 'ADD',
}

export enum STATUS_ASSIGMENT {
  ASIGNACION = 'ASIGNACION',
  DEVOLUCION = 'DEVOLUCION',
}

export enum STATUS_RESOURCE {
  BUENO = 'BUENO',
  DEVOLUCION = 'DEVOLUCION',
}

export enum STATUS_ENTRIES {
  IN_TRANSIT = 'IN_TRANSIT',
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
  IN_MAINTENANCE = 'IN_MAINTENANCE',
  IN_WAREHOUSE = 'IN_WAREHOUSE',
}
export enum MAITENANCE_TYPE {
  CORRECTIVO = 'CORRECTIVO',
  PREVENTIVO = 'PREVENTIVO',
}

export enum STATUS_MANTENANCE {
  EN_OPERACION = 'EN_OPERACION',
  EN_ALMACEN = 'EN_ALMACEN',
}

export enum ADD_REMOVE {
  ALTA = 'ALTA',
  BAJA = 'BAJA',
}

export enum STATUS_INVENTORY {
  EN_ALMACEN = 'EN_ALMACEN',
  EN_OPERACION = 'EN_OPERACION',
}
export enum ASSIGNMENT_STATUS {
  ASIGNACION = 'ASIGNACION',
  DEVOLUCION = 'DEVOLUCION',
}
